"""Emit a CaST program that runs one 5x5 MNIST tile on the systolic array.

Reads ml/mnist_model.json (produced by train_mnist_mlp.py) and writes

    examples/mnist_tile.cast              the program
    tests/expected/mnist_tile.expected    the output PyTorch says it must print

The array is the same output-stationary design as examples/systolic_matmul.cast,
which is already verified on the nodes. The only new thing here is that the
weight matrix contains negative numbers.

Negatives are emitted as ``0 - 42`` rather than ``-42``: both work on the
current compiler, but the subtraction form also parses on the old one in the
node image, and it makes the two's-complement encoding explicit.

Run:  python ml/gen_cast_tile.py
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
MODEL = HERE / "mnist_model.json"
CAST_OUT = ROOT / "examples" / "mnist_tile.cast"
EXP_OUT = ROOT / "tests" / "expected" / "mnist_tile.expected"

N = 5
LAST_T = 3 * N - 2          # last cycle on which a useful MAC happens
MASK32 = (1 << 32) - 1


def lit(v):
    """A CaST literal for a possibly negative integer."""
    return str(v) if v >= 0 else f"0 - {-v}"


def gen(doc):
    x = doc["tile"]["x"]
    w = doc["tile"]["w"]
    c = doc["tile"]["c"]
    k0 = doc["tile"]["feature_offset"]
    labels = doc["reference"]["labels"]

    L = []
    add = L.append

    add(f"""\
// One 5x5 tile of MNIST layer 1, run on the output-stationary systolic array.
//
// Generated by ml/gen_cast_tile.py from a quantised PyTorch MLP
// ({doc['arch']['grid']}x{doc['arch']['grid']} pixels -> {doc['arch']['hidden']} hidden -> {doc['arch']['classes']} classes,
//  {doc['accuracy']['int'] * 100:.2f}% integer test accuracy). Do not edit by hand.
//
//   C[i][j] = sum_k  X[i][k] * W[k][j]
//     X[i][k]  pixel {k0}+k of test image i     (uint8, 0..255)
//     W[k][j]  weight pixel {k0}+k -> hidden unit j  (int8, SIGNED)
//     C[i][j]  int32 partial accumulator
//
// Test image labels: {labels}
//
// This is the signedness proof: W contains negative weights, so every printed
// value depends on negative multiplication being correct. Values are printed
// in sign-magnitude form because `print` formats wires as unsigned.

machine MnistTile {{
    interface {{}}
    shared {{
        var uint32 x[{N}][{N}];       // activations, always non-negative
        var uint32 w[{N}][{N}];       // weights, two's complement int8
        var uint32 a_pipe[{N}][{N}];
        var uint32 b_pipe[{N}][{N}];
        var uint32 c[{N}][{N}];
        var uint32 t;
    }}
    states {{
        load: {{""")

    for i in range(N):
        add(f"            // image {i} (label {labels[i]}), pixels {k0}..{k0 + N - 1}")
        add("            " + " ".join(f"x[{i}][{k}] = {x[i][k]};" for k in range(N)))
    add("")
    for k in range(N):
        add(f"            // pixel {k0 + k} -> hidden units 0..{N - 1}")
        add("            " + " ".join(f"w[{k}][{j}] = {lit(w[k][j])};" for j in range(N)))
    add(f"""
            print("MnistTile: {N}x{N} layer-1 tile, signed weights");
            goto step;
        }}

        step: {{
            // MAC: every PE accumulates the operand pair it holds.
            for (var int i = 0; i < {N}; i++) {{
                for (var int j = 0; j < {N}; j++) {{
                    c[i][j] += a_pipe[i][j] * b_pipe[i][j];
                }}
            }}

            // Activations flow left -> right, row i skewed by i cycles.
            for (var int i = 0; i < {N}; i++) {{
                for (var int j = {N - 1}; j > 0; j--) {{
                    a_pipe[i][j] = a_pipe[i][j - 1];
                }}
                if (t >= i && t < i + {N}) {{
                    a_pipe[i][0] = x[i][t - i];
                }} else {{
                    a_pipe[i][0] = 0;
                }}
            }}

            // Weights flow top -> bottom, column j skewed by j cycles.
            for (var int j = 0; j < {N}; j++) {{
                for (var int i = {N - 1}; i > 0; i--) {{
                    b_pipe[i][j] = b_pipe[i - 1][j];
                }}
                if (t >= j && t < j + {N}) {{
                    b_pipe[0][j] = w[t - j][j];
                }} else {{
                    b_pipe[0][j] = 0;
                }}
            }}

            t++;
            // t reads its start-of-cycle value here, so the MAC at t == {LAST_T}
            // still runs before we leave.
            if (t < {LAST_T}) {{
                goto step;
            }} else {{
                goto done;
            }}
        }}

        done: {{
            print("C = X * W:");
            goto e_0_0;
        }}
""")

    # One element per state: prints in the same state fire on one clock edge
    # and Verilog does not order them.
    for i in range(N):
        for j in range(N):
            nxt = f"e_{i}_{j + 1}" if j + 1 < N else (
                f"e_{i + 1}_0" if i + 1 < N else "halt")
            add(f"""\
        e_{i}_{j}: {{
            // `< 0` is an unsigned compare and would never fire, so test the
            // sign bit. >> is logical, which is exactly what is wanted here.
            if ((c[{i}][{j}] >> 31) == 1) {{
                print("  C[{i}][{j}] = -", 0 - c[{i}][{j}]);
            }} else {{
                print("  C[{i}][{j}] = ", c[{i}][{j}]);
            }}
            goto {nxt};
        }}""")

    add(f"""
        halt: {{
            goto halt;
        }}
    }}
}}

instantiate {{
    tile = MnistTile();
}}
""")
    expected = ["MnistTile: 5x5 layer-1 tile, signed weights", "C = X * W:"]
    for i in range(N):
        for j in range(N):
            v = c[i][j]
            expected.append(f"  C[{i}][{j}] = -{-v}" if v < 0
                            else f"  C[{i}][{j}] = {v}")
    return "\n".join(L) + "\n", "\n".join(expected) + "\n"


def main():
    doc = json.loads(MODEL.read_text())
    src, expected = gen(doc)
    CAST_OUT.write_text(src)
    EXP_OUT.write_text(expected)
    print(f"wrote {CAST_OUT}")
    print(f"wrote {EXP_OUT}")


if __name__ == "__main__":
    main()
