"""Emit the full MNIST inference program for the CaST hexagonal systolic array.

Reads ml/mnist_model.json and writes

    examples/mnist_mlp_hex.cast             the program
    tests/expected/mnist_mlp_hex.expected   what PyTorch says it must print

Only the constant tables are generated. The state machine below is written
out literally, because the hexagonal array is the point of the exercise and
should be readable as hardware rather than as generated text.

Run:  python ml/gen_cast_mlp.py
"""

import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
MODEL = HERE / "mnist_model.json"
CAST_OUT = ROOT / "examples" / "mnist_mlp_hex.cast"
EXP_OUT = ROOT / "tests" / "expected" / "mnist_mlp_hex.expected"

N = 5              # systolic tile size
SPAN = 2 * N - 1   # bounding box of the hexagon: 9x9 for N=5
LAST_T = 3 * (N - 1)   # last cycle on which a product is captured


def u32(v):
    """Two's complement image of a signed value in a 32-bit CaST register."""
    return v & 0xFFFFFFFF


def rows(name, idx, block):
    """One source line per matrix row of a 5x5 tile."""
    return [f"            " + " ".join(
        f"{name}[{idx}][{r}][{c}] = {u32(block[r][c])};" for c in range(N))
        for r in range(N)]


def constants(doc):
    T = doc["tiles"]
    a = doc["arch"]
    L = []
    L.append("            // Pixels: xt[batch * %d + k-tile][image in batch][pixel]."
             % a["kt1"])
    for kt, blk in enumerate(T["x"]):
        L += rows("xt", kt, blk)
    L.append("")
    L.append("            // Layer 1 weights: w1t[k-tile * %d + j-tile][pixel][unit]."
             % a["jt1"])
    for i, blk in enumerate(T["w1"]):
        L += rows("w1t", i, blk)
    L.append("")
    L.append("            // Layer 1 bias, in accumulator units.")
    for jt, b in enumerate(T["b1"]):
        L.append("            " + " ".join(
            f"b1t[{jt}][{c}] = {u32(v)};" for c, v in enumerate(b)))
    L.append("")
    L.append("            // Layer 2 weights: w2t[k-tile * %d + j-tile][unit][class]."
             % a["jt2"])
    for i, blk in enumerate(T["w2"]):
        L += rows("w2t", i, blk)
    L.append("")
    L.append("            // Layer 2 bias.")
    for jt, b in enumerate(T["b2"]):
        L.append("            " + " ".join(
            f"b2t[{jt}][{c}] = {u32(v)};" for c, v in enumerate(b)))
    L.append("")
    L.append("            // True labels, printed alongside each guess and")
    L.append("            // compared against it to keep the running score.")
    labels = doc["reference"]["labels"]
    for i in range(0, len(labels), 10):
        L.append("            " + " ".join(
            f"lbl[{i + o}] = {v};" for o, v in enumerate(labels[i:i + 10])))
    return "\n".join(L)


def gen(doc):
    a, sh = doc["arch"], doc["shift"]
    kt1, jt1, kt2, jt2 = a["kt1"], a["jt1"], a["kt2"], a["jt2"]
    nimg, nb = a["images"], a["nb"]

    # Exact run length, so the documented --duration never goes stale.
    #   pass  = stage + steps + accum, where `step` runs for t = 0..LAST_T
    #           inclusive, so LAST_T + 1 cycles
    #   batch = clear + layer 1 passes + epilogue1 + layer 2 passes
    #           + epilogue2 + argmax + N report cycles
    per_pass = LAST_T + 3
    per_batch = 4 + N + per_pass * (kt1 * jt1 + kt2 * jt2)
    # `cyc` in the program below counts exactly these: setup plus every batch.
    # The five summary states do not tick it, so it reports the cost of the
    # work rather than the cost of printing the report.
    work = 1 + nb * per_batch
    cycles = work + 5
    duration = -(-cycles * 10 // 100000) * 100000     # round up to 100k ns

    # Useful multiply-accumulates. Every dimension is a multiple of the tile
    # size, so no pass is padded and none of this is wasted work.
    macs = nimg * (a["in_dim"] * a["hidden"] + a["hidden"] * a["classes"])
    per_img = f"{work / nimg:.1f}"
    density = f"{macs / work:.1f}"

    # With exactly 100 images the count of correct guesses is already the
    # percentage, which saves synthesising a divider for the summary line.
    if nimg == 100:
        pct = ("            // 100 images, so the score is already a percentage --\n"
               "            // no divider needed.\n"
               '            print("accuracy: ", ncorrect, "%");')
    else:
        pct = f'            print("accuracy: ", (ncorrect * 100) / {nimg}, "%");'

    src = f"""\
// MNIST inference on a hexagonal systolic array.
//
// Generated by ml/gen_cast_mlp.py from a quantised PyTorch MLP. Do not edit
// by hand -- change the model and regenerate.
//
//   {a['grid']}x{a['grid']} pixels ({a['in_dim']}) -> {a['hidden']} hidden (ReLU) -> {a['classes']} classes
//   {doc['accuracy']['int'] * 100:.2f}% integer test accuracy ({doc['accuracy']['float'] * 100:.2f}% in float)
//
// {nimg} test images are classified, {N} at a time -- {N} images is exactly the
// array's width, so each pass computes a {N}x{N} block of (images x units).
// The {nb} batches run one after another through the same array; only the
// pixels and labels are stored per image, the accumulators are reused.
// A running score is kept and reported at the end.
//
// Arithmetic. Everything is a uint32 register holding a two's complement
// int32. Multiply and add are sign-agnostic in two's complement, so the
// systolic MAC needs no special handling for negative weights. The three
// places that DO care about sign are called out where they appear:
// the ReLU sign test, the requantising shift, and the argmax compare.
//
// Timing. A free-running counter reports the cycles the classification
// actually took, so the figure is measured rather than asserted. It comes to
// {work} cycles for {nimg} images ({per_img} each), during which the array
// performs {macs} multiply-accumulates -- {density} per cycle. The whole
// program including the printed summary is {cycles} cycles ({cycles * 10} ns).
//
// The default 500 ns would stop this after 50 cycles, so the run needs a
// long --duration. simulate.sh reads the line below and applies it, so
//
//     ./simulate.sh examples/mnist_mlp_hex.cast
//
// is enough; passing --duration explicitly still overrides it.
//
// simulate: --duration={duration}

machine MnistMLP {{
    interface {{}}
    shared {{
        // ---- model constants, written once in `setup` -------------------
        var uint32 xt[{nb * kt1}][{N}][{N}];
        var uint32 w1t[{kt1 * jt1}][{N}][{N}];
        var uint32 b1t[{jt1}][{N}];
        var uint32 w2t[{kt2 * jt2}][{N}][{N}];
        var uint32 b2t[{jt2}][{N}];
        var uint32 lbl[{nimg}];

        // ---- the hexagonal array ----------------------------------------
        var uint32 ha[{SPAN}][{SPAN}];   // A operands in flight
        var uint32 hb[{SPAN}][{SPAN}];   // B operands in flight
        var uint32 hc[{SPAN}][{SPAN}];   // partial sums in flight
        var uint32 hr[{SPAN}][{SPAN}];   // this cycle's MAC at each PE
        var uint32 opA[{N}][{N}];        // operands staged for this tile
        var uint32 opB[{N}][{N}];
        var uint32 hout[{N}][{N}];       // captured tile product
        var uint32 t;                    // cycle within the current pass

        // ---- accumulators and control -----------------------------------
        var uint32 acc1[{jt1}][{N}][{N}];
        var uint32 acc2[{jt2}][{N}][{N}];
        var uint32 kt;
        var uint32 jt;
        var uint32 layer;
        var uint32 ib;                   // which batch of {N} images
        var uint32 ncorrect;             // running score
        var uint32 best[{N}];
        var uint32 pred[{N}];
        var uint32 pi;

        // ---- cycle counter ------------------------------------------------
        // Ticks once in every state that does classification work, which is
        // one tick per clock cycle. The summary states at the bottom leave it
        // alone, so it stops at the cost of the work itself and does not
        // count the cycles spent printing the report.
        var uint32 cyc;
    }}
    states {{
        setup: {{
{constants(doc)}

            // `cyc` is set rather than incremented: this state IS cycle 1,
            // and an explicit write does not depend on the reset value.
            ib = 0; ncorrect = 0; cyc = 1;
            print("MnistMLP: {nimg} images, {a['in_dim']} pixels -> {a['hidden']} hidden -> {a['classes']} classes");
            goto batch;
        }}

        // Start a batch of {N} images. The array and the weights are shared
        // across all {nb} batches; only the accumulators need clearing.
        batch: {{
            for (var int p = 0; p < {jt1}; p++) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int j = 0; j < {N}; j++) {{ acc1[p][i][j] = 0; }}
                }}
            }}
            for (var int p = 0; p < {jt2}; p++) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int c = 0; c < {N}; c++) {{ acc2[p][i][c] = 0; }}
                }}
            }}
            layer = 1; kt = 0; jt = 0; pi = 0; cyc++;
            goto stage;
        }}

        // Stage one {N}x{N} operand pair and clear the array. The very first
        // pair is placed directly on the hexagon's apex PE({N - 1},{N - 1}); every later
        // pair is injected by `step` on the cycle before it is needed.
        stage: {{
            if (layer == 1) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int k = 0; k < {N}; k++) {{
                        opA[i][k] = xt[ib * {kt1} + kt][i][k];
                    }}
                }}
                for (var int k = 0; k < {N}; k++) {{
                    for (var int j = 0; j < {N}; j++) {{
                        opB[k][j] = w1t[kt * {jt1} + jt][k][j];
                    }}
                }}
            }} else {{
                // Layer 2's activations are layer 1's accumulators, already
                // partitioned the same way: j-tiles of hidden units become
                // k-tiles of layer 2 inputs.
                for (var int i = 0; i < {N}; i++) {{
                    for (var int k = 0; k < {N}; k++) {{
                        opA[i][k] = acc1[kt][i][k];
                    }}
                }}
                for (var int k = 0; k < {N}; k++) {{
                    for (var int j = 0; j < {N}; j++) {{
                        opB[k][j] = w2t[kt * {jt2} + jt][k][j];
                    }}
                }}
            }}

            for (var int U = 0; U < {SPAN}; U++) {{
                for (var int V = 0; V < {SPAN}; V++) {{
                    ha[U][V] = 0; hb[U][V] = 0; hc[U][V] = 0;
                }}
            }}
            // Overrides the zero written just above: later writes win.
            if (layer == 1) {{
                ha[{N - 1}][{N - 1}] = xt[ib * {kt1} + kt][0][0];
                hb[{N - 1}][{N - 1}] = w1t[kt * {jt1} + jt][0][0];
            }} else {{
                ha[{N - 1}][{N - 1}] = acc1[kt][0][0];
                hb[{N - 1}][{N - 1}] = w2t[kt * {jt2} + jt][0][0];
            }}
            t = 0; cyc++;
            goto step;
        }}

        // ------------------------------------------------------------------
        // One cycle of the hexagonal (Kung-Leiserson) array.
        //
        // C[i][j] += A[i][k]*B[k][j] has a {N}x{N}x{N} iteration space. Project that
        // cube along its (1,1,1) diagonal and schedule iteration (i,j,k) at
        // time t = i+j+k. Each operand then travels along one of three axes
        // 120 degrees apart, one PE per cycle:
        //
        //     PE(U,V) = (i-k+{N - 1}, j-k+{N - 1})        U,V in 0..{SPAN - 1}
        //
        //     A[i][k] -> +V        B[k][j] -> +U        C[i][j] -> (-1,-1)
        //
        // Nothing is stationary. Unlike the square array in
        // systolic_matmul.cast, where C sits still and only the operands
        // move, here the partial sums stream through as well -- that is what
        // makes the connectivity hexagonal, six neighbours per PE.
        //
        // The live sites form a hexagon inside the {SPAN}x{SPAN} box ({3 * N * N - 3 * N + 1} of {SPAN * SPAN});
        // the corners stay zero. Because the projection direction equals the
        // schedule vector, a PE holds a matching (i,j,k) triple only every
        // third cycle. On the other two it passes data through, and the
        // partial sums riding those slots are never captured.
        //
        // The five blocks below are the five wires of one PE, written once
        // and replicated by the unroller.
        // ------------------------------------------------------------------
        step: {{
            // 1. Multiply-accumulate. Nothing below has written ha, hb or hc
            //    yet, so every PE reads its start-of-cycle operands and the
            //    whole array acts at once, as the hardware would.
            for (var int U = 0; U < {SPAN}; U++) {{
                for (var int V = 0; V < {SPAN}; V++) {{
                    hr[U][V] = hc[U][V] + ha[U][V] * hb[U][V];
                }}
            }}

            // 2. A advances one PE in +V. Iterate V downwards so each PE
            //    reads its neighbour's pre-shift value.
            for (var int U = 0; U < {SPAN}; U++) {{
                for (var int V = {SPAN - 1}; V > 0; V--) {{ ha[U][V] = ha[U][V - 1]; }}
                ha[U][0] = 0;
            }}

            // 3. B advances one PE in +U.
            for (var int V = 0; V < {SPAN}; V++) {{
                for (var int U = {SPAN - 1}; U > 0; U--) {{ hb[U][V] = hb[U - 1][V]; }}
                hb[0][V] = 0;
            }}

            // 4. Partial sums advance one PE in (-1,-1), carrying the MAC
            //    just computed. The far edges feed in empty slots.
            for (var int U = 0; U < {SPAN - 1}; U++) {{
                for (var int V = 0; V < {SPAN - 1}; V++) {{ hc[U][V] = hr[U + 1][V + 1]; }}
                hc[U][{SPAN - 1}] = 0;
            }}
            for (var int V = 0; V < {SPAN}; V++) {{ hc[{SPAN - 1}][V] = 0; }}

            // 5. Inject the operands that must be in place next cycle.
            //    A[i][k] enters the hexagon where j == 0, at PE(i+V, V) with
            //    V = {N - 1}-k; B[k][j] enters where i == 0, at PE(U, U+j) with
            //    U = {N - 1}-k. Both the site and the arrival time are compile-time
            //    constants, so this costs one comparison against t per edge.
            for (var int V = 0; V < {N}; V++) {{
                for (var int i = 0; i < {N}; i++) {{
                    if (t + 1 + V == i + {N - 1}) {{ ha[i + V][V] = opA[i][{N - 1} - V]; }}
                }}
            }}
            for (var int U = 0; U < {N}; U++) {{
                for (var int j = 0; j < {N}; j++) {{
                    if (t + 1 + U == j + {N - 1}) {{ hb[U][U + j] = opB[{N - 1} - U][j]; }}
                }}
            }}

            // 6. A fresh zero accumulator enters at PE(i+{N - 1}, j+{N - 1}) for the
            //    k == 0 term of C[i][j].
            for (var int i = 0; i < {N}; i++) {{
                for (var int j = 0; j < {N}; j++) {{
                    if (t + 1 == i + j) {{ hc[i + {N - 1}][j + {N - 1}] = 0; }}
                }}
            }}

            // 7. C[i][j] is finished by its k == {N - 1} term, which lands on
            //    PE(i,j) at t = i+j+{N - 1}. Catch it as it leaves.
            for (var int i = 0; i < {N}; i++) {{
                for (var int j = 0; j < {N}; j++) {{
                    if (t == i + j + {N - 1}) {{ hout[i][j] = hr[i][j]; }}
                }}
            }}

            t++; cyc++;
            // t reads its start-of-cycle value, so the pass ends after the
            // cycle that captured C[{N - 1}][{N - 1}].
            if (t < {LAST_T}) {{ goto step; }} else {{ goto accum; }}
        }}

        // Fold the tile product into the running sum and step the tile
        // indices. One systolic pass covers k-tile `kt` of output block `jt`.
        accum: {{
            if (layer == 1) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int j = 0; j < {N}; j++) {{ acc1[jt][i][j] += hout[i][j]; }}
                }}
            }} else {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int j = 0; j < {N}; j++) {{ acc2[jt][i][j] += hout[i][j]; }}
                }}
            }}

            kt++; cyc++;
            // kt and jt read their start-of-cycle values, so both tests
            // compare against the last index rather than the count.
            if (layer == 1) {{
                if (kt < {kt1 - 1}) {{
                    goto stage;
                }} else {{
                    kt = 0; jt++;
                    if (jt < {jt1 - 1}) {{ goto stage; }} else {{ goto epilogue1; }}
                }}
            }} else {{
                if (kt < {kt2 - 1}) {{
                    goto stage;
                }} else {{
                    kt = 0; jt++;
                    if (jt < {jt2 - 1}) {{ goto stage; }} else {{ goto epilogue2; }}
                }}
            }}
        }}

        // Layer 1 epilogue: bias, ReLU, requantise to uint8. acc1 is
        // rewritten in place and becomes the layer 2 activations.
        //
        // Reads inside a loop body see writes made earlier in the same body,
        // so these four steps chain within one cycle.
        epilogue1: {{
            for (var int p = 0; p < {jt1}; p++) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int j = 0; j < {N}; j++) {{
                        acc1[p][i][j] += b1t[p][j];
                        // SIGN 1: `< 0` would be an unsigned compare and
                        // never fire. Test the sign bit instead.
                        if ((acc1[p][i][j] >> 31) == 1) {{ acc1[p][i][j] = 0; }}
                        // SIGN 2: >> is a logical shift. That is only correct
                        // because ReLU just guaranteed a non-negative value.
                        acc1[p][i][j] = acc1[p][i][j] >> {sh};
                        if (acc1[p][i][j] > 255) {{ acc1[p][i][j] = 255; }}
                    }}
                }}
            }}
            layer = 2; kt = 0; jt = 0; cyc++;
            goto stage;
        }}

        // Layer 2 epilogue: bias, then offset every logit by 2^31.
        //
        // SIGN 3: flipping the sign bit maps int32 ordering onto uint32
        // ordering exactly, so the unsigned compares in `argmax` below rank
        // the logits the way a signed compare would.
        epilogue2: {{
            for (var int p = 0; p < {jt2}; p++) {{
                for (var int i = 0; i < {N}; i++) {{
                    for (var int c = 0; c < {N}; c++) {{
                        acc2[p][i][c] = (acc2[p][i][c] + b2t[p][c]) + (1 << 31);
                    }}
                }}
            }}
            cyc++;
            goto argmax;
        }}

        argmax: {{
            for (var int i = 0; i < {N}; i++) {{
                best[i] = 0;
                pred[i] = 0;
                for (var int p = 0; p < {jt2}; p++) {{
                    for (var int c = 0; c < {N}; c++) {{
                        if (acc2[p][i][c] > best[i]) {{
                            best[i] = acc2[p][i][c];
                            pred[i] = p * {N} + c;
                        }}
                    }}
                }}
            }}
            cyc++;
            goto report;
        }}

        // Score and report this batch, one image per cycle with a runtime
        // `goto` loop -- prints issued in the same state share a clock edge
        // and Verilog leaves their order undefined.
        //
        // The two prints below are in mutually exclusive branches, so only
        // one fires per cycle.
        report: {{
            if (pred[pi] == lbl[ib * {N} + pi]) {{
                ncorrect++;
                print("image ", ib * {N} + pi, "  label ", lbl[ib * {N} + pi],
                      "  guess ", pred[pi], "  ok");
            }} else {{
                print("image ", ib * {N} + pi, "  label ", lbl[ib * {N} + pi],
                      "  guess ", pred[pi], "  WRONG");
            }}
            pi++; cyc++;
            // pi and ib read their start-of-cycle values, so both tests
            // compare against the last index rather than the count.
            if (pi < {N - 1}) {{
                goto report;
            }} else {{
                ib++;
                if (ib < {nb - 1}) {{ goto batch; }} else {{ goto summary; }}
            }}
        }}

        summary: {{
            print("correct: ", ncorrect, " of {nimg}");
            goto summary_pct;
        }}

        summary_pct: {{
{pct}
            goto summary_cyc;
        }}

        // Timing, for comparison against other hardware. None of the summary
        // states tick `cyc`, so it still holds the value it reached when the
        // last image was scored -- the cost of the work, not of the report.
        summary_cyc: {{
            print("cycles: ", cyc);
            goto summary_img;
        }}

        // Derived figures. These are compile-time constants rather than
        // runtime arithmetic: a divider is a lot of hardware for a line of
        // text, and the measured count above is what validates them.
        summary_img: {{
            print("cycles per image: {per_img}");
            goto summary_mac;
        }}

        // {macs} = {nimg} images x ({a['in_dim']}x{a['hidden']} + {a['hidden']}x{a['classes']}) multiply-accumulates.
        // Every dimension is a multiple of {N}, so no pass is padded and none
        // of this is wasted work.
        summary_mac: {{
            print("MACs: {macs} ({density} per cycle)");
            goto halt;
        }}

        halt: {{ goto halt; }}
    }}
}}

instantiate {{
    mlp = MnistMLP();
}}
"""

    ref = doc["reference"]
    exp = [f"MnistMLP: {nimg} images, {a['in_dim']} pixels -> "
           f"{a['hidden']} hidden -> {a['classes']} classes"]
    ncorrect = 0
    for i in range(nimg):
        lab, pre = ref["labels"][i], ref["pred"][i]
        hit = "ok" if lab == pre else "WRONG"
        ncorrect += lab == pre
        exp.append(f"image {i}  label {lab}  guess {pre}  {hit}")
    assert ncorrect == ref["correct"]
    exp.append(f"correct: {ncorrect} of {nimg}")
    exp.append(f"accuracy: {ncorrect * 100 // nimg}%")
    # The cycle count is measured by the program, so this line is a real
    # prediction: if the schedule ever changes, the diff catches it here.
    exp.append(f"cycles: {work}")
    exp.append(f"cycles per image: {per_img}")
    exp.append(f"MACs: {macs} ({density} per cycle)")
    return src, "\n".join(exp) + "\n"


def main():
    doc = json.loads(MODEL.read_text())
    src, expected = gen(doc)
    CAST_OUT.write_text(src)
    EXP_OUT.write_text(expected)
    print(f"wrote {CAST_OUT}  ({len(src.splitlines())} lines)")
    print(f"wrote {EXP_OUT}  ({len(expected.splitlines())} lines)")


if __name__ == "__main__":
    main()
