// Generated by CIRCT 7f76cbc26
module RunningAverage(
  input         clk,
                rst,
  input  [15:0] value,
  input         value_valid,
  input  [15:0] test,
  input         test_valid,
  output        value_ready,
                test_ready
);

  wire        _GEN;
  wire [15:0] _GEN_0;
  wire [31:0] _GEN_1;
  reg  [31:0] _GEN_2;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_2 <= 32'h0;
    else
      _GEN_2 <= _GEN_1;
  end // always_ff @(posedge)
  reg  [15:0] _GEN_3;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_3 <= 16'h0;
    else
      _GEN_3 <= _GEN_0;
  end // always_ff @(posedge)
  reg         _GEN_4;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_4 <= 1'h0;
    else
      _GEN_4 <= _GEN;
  end // always_ff @(posedge)
  wire        _GEN_5 = _GEN_4 == 1'h0;
  wire        _GEN_6 = _GEN_5 & value_valid;
  always_ff @(posedge clk) begin
    if (_GEN_6)
      $fwrite(32'h80000001, "  sample[%0d] = %0d  running total = %0d\n", _GEN_3, value,
              _GEN_2);
  end // always_ff @(posedge)
  wire        _GEN_7 = _GEN_6 & {16'h0, _GEN_3} == 32'h8;
  always_ff @(posedge clk) begin
    if (_GEN_7)
      $fwrite(32'h80000001, "average of 8 samples: %0d\n", _GEN_2 >> 32'h3);
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (_GEN_7)
      $fwrite(32'h80000001, "--- resetting ---\n");
  end // always_ff @(posedge)
  assign _GEN_1 = _GEN_7 ? 32'h0 : _GEN_6 ? _GEN_2 + {16'h0, value} : _GEN_2;
  assign _GEN_0 = _GEN_7 ? 16'h0 : _GEN_6 ? _GEN_3 + 16'h1 : _GEN_3;
  assign _GEN = _GEN_6 ? 1'h0 : _GEN_4;
  assign value_ready = _GEN_5;
  assign test_ready = 1'h1;
endmodule

module Main(
  input clk,
        rst
);

  wire        outputRdEn;
  wire        inputEn;
  wire [2:0]  fifo_rd_addr_next;
  wire [2:0]  fifo_wr_addr_next;
  wire [2:0]  fifo_count_next;
  reg  [2:0]  fifo_wr_addr;
  wire        outputRdEn_0;
  wire        inputEn_0;
  wire [2:0]  fifo_rd_addr_next_0;
  wire [2:0]  fifo_wr_addr_next_0;
  wire [2:0]  fifo_count_next_0;
  reg  [2:0]  fifo_wr_addr_0;
  wire        _r_value_ready;
  wire        _r_test_ready;
  reg  [15:0] _GEN;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN <= 16'h2A;
    else
      _GEN <= 16'h2A;
  end // always_ff @(posedge)
  reg         _GEN_0;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_0 <= 1'h1;
    else
      _GEN_0 <= 1'h1;
  end // always_ff @(posedge)
  reg  [2:0]  fifo_count;
  always_ff @(posedge clk) begin
    if (rst)
      fifo_count <= 3'h0;
    else
      fifo_count <= fifo_count_next_0;
  end // always_ff @(posedge)
  reg  [15:0] fifo_mem[0:4];
  always_ff @(posedge clk) begin
    if (rst) begin
    end
    else begin
      if (inputEn_0)
        fifo_mem[fifo_wr_addr_0] <= _GEN;
    end
  end // always_ff @(posedge)
  reg  [2:0]  fifo_rd_addr;
  always_ff @(posedge clk) begin
    if (rst)
      fifo_rd_addr <= 3'h0;
    else
      fifo_rd_addr <= fifo_rd_addr_next_0;
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (rst)
      fifo_wr_addr_0 <= 3'h0;
    else
      fifo_wr_addr_0 <= fifo_wr_addr_next_0;
  end // always_ff @(posedge)
  wire        fifo_full = fifo_count == 3'h5;
  wire        fifo_empty = fifo_count == 3'h0;
  wire        _GEN_1 = ~outputRdEn_0;
  wire        _GEN_2 = ~inputEn_0;
  assign fifo_count_next_0 =
    _GEN_1 & _GEN_2
      ? fifo_count
      : inputEn_0 & _GEN_1
          ? (fifo_count == 3'h5 ? fifo_count : fifo_count + 3'h1)
          : outputRdEn_0 & _GEN_2
              ? (fifo_count == 3'h0 ? fifo_count : fifo_count - 3'h1)
              : fifo_count;
  wire [2:0]  _GEN_3 = inputEn_0 & ~fifo_full ? fifo_wr_addr_0 + 3'h1 : fifo_wr_addr_0;
  assign fifo_wr_addr_next_0 = _GEN_3 == 3'h5 ? 3'h0 : _GEN_3;
  wire [2:0]  _GEN_4 = outputRdEn_0 & ~fifo_empty ? fifo_rd_addr + 3'h1 : fifo_rd_addr;
  assign fifo_rd_addr_next_0 = _GEN_4 == 3'h5 ? 3'h0 : _GEN_4;
  FIFO_empty_when_read_enabled:
    assert property (@(posedge clk) ~(outputRdEn_0 & fifo_empty));
  FIFO_full_when_write_enabled: assert property (@(posedge clk) ~(inputEn_0 & fifo_full));
  assign inputEn_0 = _GEN_0 & ~fifo_full;
  wire        _GEN_5 = ~fifo_empty;
  assign outputRdEn_0 = _GEN_5 & _r_value_ready;
  reg  [15:0] _GEN_6;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_6 <= 16'h0;
    else
      _GEN_6 <= 16'h0;
  end // always_ff @(posedge)
  reg         _GEN_7;
  always_ff @(posedge clk) begin
    if (rst)
      _GEN_7 <= 1'h0;
    else
      _GEN_7 <= 1'h0;
  end // always_ff @(posedge)
  reg  [2:0]  fifo_count_0;
  always_ff @(posedge clk) begin
    if (rst)
      fifo_count_0 <= 3'h0;
    else
      fifo_count_0 <= fifo_count_next;
  end // always_ff @(posedge)
  reg  [15:0] fifo_mem_0[0:4];
  always_ff @(posedge clk) begin
    if (rst) begin
    end
    else begin
      if (inputEn)
        fifo_mem_0[fifo_wr_addr] <= _GEN_6;
    end
  end // always_ff @(posedge)
  reg  [2:0]  fifo_rd_addr_0;
  always_ff @(posedge clk) begin
    if (rst)
      fifo_rd_addr_0 <= 3'h0;
    else
      fifo_rd_addr_0 <= fifo_rd_addr_next;
  end // always_ff @(posedge)
  always_ff @(posedge clk) begin
    if (rst)
      fifo_wr_addr <= 3'h0;
    else
      fifo_wr_addr <= fifo_wr_addr_next;
  end // always_ff @(posedge)
  wire        fifo_full_0 = fifo_count_0 == 3'h5;
  wire        fifo_empty_0 = fifo_count_0 == 3'h0;
  wire        _GEN_8 = ~outputRdEn;
  wire        _GEN_9 = ~inputEn;
  assign fifo_count_next =
    _GEN_8 & _GEN_9
      ? fifo_count_0
      : inputEn & _GEN_8
          ? (fifo_count_0 == 3'h5 ? fifo_count_0 : fifo_count_0 + 3'h1)
          : outputRdEn & _GEN_9
              ? (fifo_count_0 == 3'h0 ? fifo_count_0 : fifo_count_0 - 3'h1)
              : fifo_count_0;
  wire [2:0]  _GEN_10 = inputEn & ~fifo_full_0 ? fifo_wr_addr + 3'h1 : fifo_wr_addr;
  assign fifo_wr_addr_next = _GEN_10 == 3'h5 ? 3'h0 : _GEN_10;
  wire [2:0]  _GEN_11 =
    outputRdEn & ~fifo_empty_0 ? fifo_rd_addr_0 + 3'h1 : fifo_rd_addr_0;
  assign fifo_rd_addr_next = _GEN_11 == 3'h5 ? 3'h0 : _GEN_11;
  FIFO_empty_when_read_enabled_0:
    assert property (@(posedge clk) ~(outputRdEn & fifo_empty_0));
  FIFO_full_when_write_enabled_0:
    assert property (@(posedge clk) ~(inputEn & fifo_full_0));
  assign inputEn = _GEN_7 & ~fifo_full_0;
  wire        _GEN_12 = ~fifo_empty_0;
  assign outputRdEn = _GEN_12 & _r_test_ready;
  RunningAverage r (
    .clk         (clk),
    .rst         (rst),
    .value       (fifo_mem[fifo_rd_addr]),
    .value_valid (_GEN_5),
    .test        (fifo_mem_0[fifo_rd_addr_0]),
    .test_valid  (_GEN_12),
    .value_ready (_r_value_ready),
    .test_ready  (_r_test_ready)
  );
endmodule

